Renamed WebAuthnManager.Config to WebAuthnManager.Configuration
swift-server/webauthn-swift pull request #43
Opened 2024-02-19 14:29 UTC by dimitribouniol

Renamed `WebAuthnManager.Config` to `WebAuthnManager.Configuration` to better match the rest of the ecosystem.

2024-02-19 15:13 UTC, dimitribouniol commented
> This would be a breaking change, but given the library is v0.x.x it doesn't matter so much.
> 
> Is it worthwhile adding in CI for catching breaking changes now?

@0xTim said it should be fine due to alpha status: https://swift-open-source.slack.com/archives/C06L689TJ3A/p1708352712434729?thread_ts=1708352246.345259&cid=C06L689TJ3A

There are a probably a few other areas of API improvement I'll be suggesting over the next few days — would the CI step make those harder? If not I agree putting something in place now would be a good call, if only to point them out.

2024-02-22 10:14 UTC, dimitribouniol commented
@adam-fowler Filed #50 for adding the CI step so we don't forget.

2024-02-27 04:44 UTC, marius-se commented
Happy with renaming `Config` to `Configuration`! But I'm not sure how we handle breaking API changes in an alpha version, I'd hand that over to @0xTim

2024-02-27 04:49 UTC, marius-se commented
> There are a probably a few other areas of API improvement I'll be suggesting over the next few days

Talking about other breaking API changes: I absolutely hate the fact that `finishRegistration` is `async` just because of `confirmCredentialIDNotRegisteredYet`. I built this back then because of step 26 [in the registration spec](https://w3c.github.io/webauthn/#reg-ceremony-assess-trust). I'd love to force the user to perform the check, but is it worth it? What do you think @dimitribouniol?

2024-02-27 07:45 UTC, dimitribouniol commented
> Talking about other breaking API changes: I absolutely hate the fact that `finishRegistration` is `async` just because of `confirmCredentialIDNotRegisteredYet`. I built this back then because of step 26 [in the registration spec](https://w3c.github.io/webauthn/#reg-ceremony-assess-trust). I'd love to force the user to perform the check, but is it worth it? What do you think @dimitribouniol?

I think it's worth keeping around as it calls out the verification the caller must make to ensure uniqueness to prevent a known (and trivial) attack surface. That said, I think we should a) document this, and b) move the main implementation which is not async to a clearly named "unsafe" (or pre-checked) variant that can be called in synchronous code when the credentialIDs have already been verified. Does this make sense?

2024-02-27 15:17 UTC, 0xTim commented
> I absolutely hate the fact that `finishRegistration` is `async` just because of `confirmCredentialIDNotRegisteredYet`

I wouldn't be too concerned over things like this and it's better to make it async and not do any async work than trying to make it work the other way around. It also opens up the possibilities of using actors without breaking the API

2024-03-20 14:24 UTC, 0xTim requested changes
One nit

2024-03-20 14:24 UTC, 0xTim commented on Sources/WebAuthn/WebAuthnManager+Config.swift
Can you update the file name too?

2024-03-20 22:32 UTC, dimitribouniol commented on Sources/WebAuthn/WebAuthnManager+Config.swift
Done!

2024-03-20 22:48 UTC, 0xTim approved these changes
Thanks!

2024-03-20 22:54 UTC, 0xTim commented
@dimitribouniol Just some merge conflicts then we're good to go

2024-03-20 22:58 UTC, dimitribouniol commented
Lemme rebase in just a moment!

2024-03-20 23:19 UTC, merged