Updated minimum deployment to Swift 5.9/macOS 13
swift-server/webauthn-swift pull request #49
Opened 2024-02-22 09:55 UTC by dimitribouniol

Updated minimum deployment to Swift 5.9/macOS 13 to support things like Duration and other modern niceties.

2024-02-27 04:53 UTC, marius-se approved these changes
LGTM 🚀

2024-02-27 13:32 UTC, 0xTim commented
@swift-server-bot please test

2024-02-27 13:33 UTC, 0xTim commented
@dimitribouniol could you update https://github.com/swift-server/webauthn-swift/tree/main/docker as well to point to 5.9 from 5.7?

2024-02-27 14:46 UTC, dimitribouniol commented
Fixed!

2024-02-28 08:08 UTC, dimitribouniol commented
@swift-server-bot please test

2024-02-28 08:09 UTC, dimitribouniol commented
(worth a try 😛)

2024-03-15 17:08 UTC, 0xTim requested changes

2024-03-15 17:08 UTC, 0xTim commented on docker/docker-compose.2204.57.yaml
Small nit - could you rename the file to reflect that its now 5.9?

2024-03-16 08:24 UTC, dimitribouniol commented on docker/docker-compose.2204.57.yaml
Done! Does the `2204` part need to change as well? Not _entirely_ sure what it refers to, but happy to bring it forward to `2403` if it's a date or something.

2024-03-17 23:53 UTC, 0xTim commented on docker/docker-compose.2204.57.yaml
It's the ubuntu version, which we will still use so all good on that front

2024-03-17 23:53 UTC, 0xTim approved these changes
Thanks!

2024-03-17 23:53 UTC, 0xTim commented
@swift-server-bot test

2024-03-17 23:54 UTC, 0xTim commented
@swift-server-bot please test

2024-03-18 16:50 UTC, yim-lee commented
@swift-server-bot add to allowlist

2024-03-18 16:52 UTC, yim-lee commented
@swift-server-bot test this please

2024-03-18 16:52 UTC, yim-lee commented
Updated CI. "pull request validation (5.9)" replaces "pull request validation (5.7)".

2024-03-18 17:04 UTC, merged

2024-03-18 22:21 UTC, dimitribouniol commented
Thanks @yim-lee!